# SITE SETTINGS
title: Tecala
description: Explore the biodiversity of Tecala
author: GBIF Secretariat                # Used for copyright statement in footer
url: "https://algae-theme.netlify.com"        # No slash at the end - Only required if your site is in a subdomain e.g. https://username.github.io
# baseurl: "/tecala"                    # Only required if your site is in a subdirectory e.g. https://username.github.io/sitename
                                        # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
                                        # A baseurl affects internal links, see http://peterdesmet.github.io/petridish/about/#links

# SOCIAL PROFILES
email: info@gbif.org                    # Social icon in footer
twitter_username: gbif                  # Social icon in footer
github_username: gbif                   # Social icon in footer

# THEME SETTINGS (ALL OPTIONAL)

tweets_on_home: true                    # Show Twitter feed of twitter_username on homepage

algae:
  logo: /assets/img/tecala_logo.png     # Logo in navbar, will be displayed with 28px height
  logoAndTitle: false
  hideHelper: false
  archive_permalink: /news/             # Permalink of page using archive.html layout, required when using post categories
  latestPostLimit: 3                    # Show x number of latest posts when showing latest posts. Defaults to 3
  style:
    square: true
    colors:
      primary: "#e86533"
      links: "#e86533"
    coloredHeadlineLinks: true

# BUILD SETTINGS
markdown: kramdown
plugins:                                # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - jekyll-theme-algae.gemspec

# FRONTMATTER DEFAULTS
defaults:
  -
    scope:
      path: "en"
    values:
      lang: en
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/post/:year/:slug/"   # Use /post/yyyy/{filename}/ as permalink for all posts
  -
    scope:
      path: ""
    values:
      layout: "page"                 # Only required for the theme website, implied for sites using a theme
